<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('items')->delete();
        
        \DB::table('items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 1,
                'item_uom_id' => 1,
                'sale_price' => 1100,
                'cost_price' => 696,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 1,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'EHF10S',
                'internal_number' => 'EHF10SCLEARDOZEN',
                'model_number' => 'EHF10SCLEAR',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 2,
                'item_uom_id' => 2,
                'sale_price' => 300,
                'cost_price' => 200,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 2,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '3716',
                'internal_number' => '3716XSPAIR',
                'model_number' => '3716G',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 2,
                'item_uom_id' => 2,
                'sale_price' => 300,
                'cost_price' => 200,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 2,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '3716',
                'internal_number' => '3716SPAIR',
                'model_number' => '3716G',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            3 => 
            array (
                'id' => 4,
                'product_id' => 2,
                'item_uom_id' => 2,
                'sale_price' => 300,
                'cost_price' => 200,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 2,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '3716',
                'internal_number' => '3716MPAIR',
                'model_number' => '3716G',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            4 => 
            array (
                'id' => 5,
                'product_id' => 2,
                'item_uom_id' => 2,
                'sale_price' => 300,
                'cost_price' => 200,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 2,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '3716',
                'internal_number' => '3716LPAIR',
                'model_number' => '3716G',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            5 => 
            array (
                'id' => 6,
                'product_id' => 2,
                'item_uom_id' => 2,
                'sale_price' => 300,
                'cost_price' => 200,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 2,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '3716',
                'internal_number' => '3716XLPAIR',
                'model_number' => '3716G',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            6 => 
            array (
                'id' => 7,
                'product_id' => 2,
                'item_uom_id' => 2,
                'sale_price' => 300,
                'cost_price' => 200,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 2,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '3716',
                'internal_number' => '37162XLPAIR',
                'model_number' => '3716G',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            7 => 
            array (
                'id' => 8,
                'product_id' => 3,
                'item_uom_id' => 3,
                'sale_price' => 500,
                'cost_price' => 378,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 5,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'LCT100',
                'internal_number' => 'LCT100BOX',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            8 => 
            array (
                'id' => 9,
                'product_id' => 4,
                'item_uom_id' => 2,
                'sale_price' => 500,
                'cost_price' => 241,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212XSPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            9 => 
            array (
                'id' => 10,
                'product_id' => 4,
                'item_uom_id' => 1,
                'sale_price' => 4300,
                'cost_price' => 4000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212XSDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            10 => 
            array (
                'id' => 11,
                'product_id' => 4,
                'item_uom_id' => 2,
                'sale_price' => 500,
                'cost_price' => 241,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212SPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            11 => 
            array (
                'id' => 12,
                'product_id' => 4,
                'item_uom_id' => 1,
                'sale_price' => 4300,
                'cost_price' => 4000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212SDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            12 => 
            array (
                'id' => 13,
                'product_id' => 4,
                'item_uom_id' => 2,
                'sale_price' => 500,
                'cost_price' => 241,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212MPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            13 => 
            array (
                'id' => 14,
                'product_id' => 4,
                'item_uom_id' => 1,
                'sale_price' => 4300,
                'cost_price' => 2150,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212MDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            14 => 
            array (
                'id' => 15,
                'product_id' => 4,
                'item_uom_id' => 2,
                'sale_price' => 500,
                'cost_price' => 241,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212LPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            15 => 
            array (
                'id' => 16,
                'product_id' => 4,
                'item_uom_id' => 1,
                'sale_price' => 4300,
                'cost_price' => 2150,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212LDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            16 => 
            array (
                'id' => 17,
                'product_id' => 4,
                'item_uom_id' => 2,
                'sale_price' => 500,
                'cost_price' => 241,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212XLPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            17 => 
            array (
                'id' => 18,
                'product_id' => 4,
                'item_uom_id' => 1,
                'sale_price' => 4300,
                'cost_price' => 2150,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '8212XLDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            18 => 
            array (
                'id' => 19,
                'product_id' => 4,
                'item_uom_id' => 2,
                'sale_price' => 500,
                'cost_price' => 241,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '82122XLPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            19 => 
            array (
                'id' => 20,
                'product_id' => 4,
                'item_uom_id' => 1,
                'sale_price' => 4300,
                'cost_price' => 2150,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '82122XLDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            20 => 
            array (
                'id' => 21,
                'product_id' => 4,
                'item_uom_id' => 2,
                'sale_price' => 500,
                'cost_price' => 241,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '82123XLPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            21 => 
            array (
                'id' => 22,
                'product_id' => 4,
                'item_uom_id' => 1,
                'sale_price' => 4300,
                'cost_price' => 2150,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 6,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '8212',
                'internal_number' => '82123XLDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            22 => 
            array (
                'id' => 23,
                'product_id' => 5,
                'item_uom_id' => 4,
                'sale_price' => 500,
                'cost_price' => 325,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 7,
                'weight' => '7.40',
                'length' => '10.00',
                'width' => '6.25',
                'height' => '10.00',
                'mpn' => 'HGBR',
                'internal_number' => 'HGBRBLACKEACH',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            23 => 
            array (
                'id' => 24,
                'product_id' => 6,
                'item_uom_id' => 4,
                'sale_price' => 160,
                'cost_price' => 124,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 8,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'S1010',
                'internal_number' => 'S1010CLEAREACH',
                'model_number' => 'S1010C',
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            24 => 
            array (
                'id' => 25,
                'product_id' => 7,
                'item_uom_id' => 4,
                'sale_price' => 1300,
                'cost_price' => 909,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 9,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '6100',
                'internal_number' => '6100SEACH',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            25 => 
            array (
                'id' => 26,
                'product_id' => 7,
                'item_uom_id' => 4,
                'sale_price' => 1300,
                'cost_price' => 909,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 9,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '6100',
                'internal_number' => '6100MEACH',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            26 => 
            array (
                'id' => 27,
                'product_id' => 7,
                'item_uom_id' => 4,
                'sale_price' => 1300,
                'cost_price' => 909,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 9,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '6100',
                'internal_number' => '6100LEACH',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            27 => 
            array (
                'id' => 28,
                'product_id' => 8,
                'item_uom_id' => 4,
                'sale_price' => 2500,
                'cost_price' => 1921,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 12,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '60923',
                'internal_number' => '60923EACH',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:57',
                'updated_at' => '2021-06-18 21:09:57',
            ),
            28 => 
            array (
                'id' => 29,
                'product_id' => 9,
                'item_uom_id' => 3,
                'sale_price' => 2300,
                'cost_price' => 1525,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 15,
                'weight' => '1.00',
                'length' => '7.00',
                'width' => '9.50',
                'height' => '4.50',
                'mpn' => 'EPFU01',
                'internal_number' => 'EPFU01ORANGEBOX',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            29 => 
            array (
                'id' => 30,
                'product_id' => 10,
                'item_uom_id' => 3,
                'sale_price' => 2100,
                'cost_price' => 1525,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 17,
                'weight' => '1.00',
                'length' => '5.50',
                'width' => '5.50',
                'height' => '7.00',
                'mpn' => 'EPFC01',
                'internal_number' => 'EPFC01ORANGEBOX',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            30 => 
            array (
                'id' => 31,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 6900,
                'cost_price' => 5000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP100',
                'internal_number' => 'MP100SCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            31 => 
            array (
                'id' => 32,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 6900,
                'cost_price' => 5000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP101',
                'internal_number' => 'MP101MCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            32 => 
            array (
                'id' => 33,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 6900,
                'cost_price' => 5000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP102',
                'internal_number' => 'MP102LCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            33 => 
            array (
                'id' => 34,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 6900,
                'cost_price' => 5000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP103',
                'internal_number' => 'MP103XLCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            34 => 
            array (
                'id' => 35,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 6900,
                'cost_price' => 5000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP104',
                'internal_number' => 'MP1042XLCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            35 => 
            array (
                'id' => 36,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 6900,
                'cost_price' => 5000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP105',
                'internal_number' => 'MP1053XLCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            36 => 
            array (
                'id' => 37,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 6900,
                'cost_price' => 5000,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP106',
                'internal_number' => 'MP1064XLCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            37 => 
            array (
                'id' => 38,
                'product_id' => 11,
                'item_uom_id' => 5,
                'sale_price' => 7100,
                'cost_price' => 5600,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 19,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => 'MP107',
                'internal_number' => 'MP1075XLCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            38 => 
            array (
                'id' => 39,
                'product_id' => 12,
                'item_uom_id' => 4,
                'sale_price' => 250,
                'cost_price' => 100,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 21,
                'weight' => '1.00',
                'length' => '5.50',
                'width' => '3.00',
                'height' => '2.00',
                'mpn' => 'SS100',
                'internal_number' => 'SS100CLEAREACH',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            39 => 
            array (
                'id' => 40,
                'product_id' => 12,
                'item_uom_id' => 1,
                'sale_price' => 2900,
                'cost_price' => 1896,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 21,
                'weight' => '1.00',
                'length' => '5.50',
                'width' => '3.00',
                'height' => '2.00',
                'mpn' => 'SS100',
                'internal_number' => 'SS100CLEARDOZEN',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            40 => 
            array (
                'id' => 41,
                'product_id' => 13,
                'item_uom_id' => 3,
                'sale_price' => 2100,
                'cost_price' => 1890,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '10.65',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8701',
                'internal_number' => '8701SBOX',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            41 => 
            array (
                'id' => 42,
                'product_id' => 13,
                'item_uom_id' => 5,
                'sale_price' => 21100,
                'cost_price' => 10550,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '10.65',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8701',
                'internal_number' => '8701SCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            42 => 
            array (
                'id' => 43,
                'product_id' => 13,
                'item_uom_id' => 3,
                'sale_price' => 2100,
                'cost_price' => 1890,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '12.10',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8702',
                'internal_number' => '8702MBOX',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            43 => 
            array (
                'id' => 44,
                'product_id' => 13,
                'item_uom_id' => 5,
                'sale_price' => 21100,
                'cost_price' => 10550,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '12.10',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8702',
                'internal_number' => '8702MCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            44 => 
            array (
                'id' => 45,
                'product_id' => 13,
                'item_uom_id' => 3,
                'sale_price' => 2500,
                'cost_price' => 2180,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '12.50',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8703',
                'internal_number' => '8703LBOX',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            45 => 
            array (
                'id' => 46,
                'product_id' => 13,
                'item_uom_id' => 5,
                'sale_price' => 24300,
                'cost_price' => 12150,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '12.50',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8703',
                'internal_number' => '8703LCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            46 => 
            array (
                'id' => 47,
                'product_id' => 13,
                'item_uom_id' => 3,
                'sale_price' => 2500,
                'cost_price' => 2180,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '13.00',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8704',
                'internal_number' => '8704XLBOX',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            47 => 
            array (
                'id' => 48,
                'product_id' => 13,
                'item_uom_id' => 5,
                'sale_price' => 24300,
                'cost_price' => 12150,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 23,
                'weight' => '13.00',
                'length' => '13.25',
                'width' => '10.25',
                'height' => '10.75',
                'mpn' => '8704',
                'internal_number' => '8704XLCASE',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            48 => 
            array (
                'id' => 49,
                'product_id' => 14,
                'item_uom_id' => 2,
                'sale_price' => 1100,
                'cost_price' => 500,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 24,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '5350',
                'internal_number' => '5350LPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            49 => 
            array (
                'id' => 50,
                'product_id' => 14,
                'item_uom_id' => 2,
                'sale_price' => 1100,
                'cost_price' => 500,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 24,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '5350',
                'internal_number' => '5350XLPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
            50 => 
            array (
                'id' => 51,
                'product_id' => 14,
                'item_uom_id' => 2,
                'sale_price' => 1100,
                'cost_price' => 500,
                'stock_status_id' => 3,
                'quantity' => 0,
                'image_id' => 24,
                'weight' => NULL,
                'length' => NULL,
                'width' => NULL,
                'height' => NULL,
                'mpn' => '5350',
                'internal_number' => '53502XLPAIR',
                'model_number' => NULL,
                'part_number' => NULL,
                'created_at' => '2021-06-18 21:09:58',
                'updated_at' => '2021-06-18 21:09:58',
            ),
        ));
        
        
    }
}